### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-node#68]
## Tasks that has be completed before the release
- [ ] Adoption of new PSBT keys and processing
- [ ] Update of fungible assets schema https://github.com/LNP-BP/rgb-node/issues/69
- [ ] Update of integration API to match the latest changes
- [ ] Update of invoice format

## Tasks before release:
- [ ] Update lower timestamp bound:
https://github.com/LNP-BP/rgb-node/blob/4e9e632c85ae808e81044b4147076879f9701ace/src/contracts/fungible/data/schema.rs#L95-L97
