### ISSUE TITLE
Implement new set of RGB schemata for fungible assets

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-node#69]
- [ ] https://github.com/LNP-BP/LNPBPs/issues/44 Restructuring asset-related RGB schemata
- [x] https://github.com/LNP-BP/LNPBPs/issues/51 introduce minimum division for LN channels/micropayments
- [x] https://github.com/LNP-BP/rgb-node/issues/17 Upgrade collectionable schemata
- [x] https://github.com/LNP-BP/rgb-node/issues/27 Burn & reissue procedures
- [x] https://github.com/LNP-BP/rgb-node/pull/19 RGB: Fungible assets reissue/replacement schema
- [x] https://github.com/LNP-BP/rgb-node/pull/20 RGB: collectible schema proposal
- [ ] (optionally) https://github.com/LNP-BP/rgb-node/pull/21 RGB: identity schema proposal
- [ ] (optionally) https://github.com/LNP-BP/rgb-node/pull/22 RGB: audit log schema proposal
