### ISSUE TITLE
Implement proper workflow PSBT data and keys

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-node#78]
- [x] Take fee from PSBT input data, not from a proprietary keys
- [x] Define standard key (pending BIP) for tweaking input key
- [x] Define proprietary information about tweak target and how the tweak should be constructed

**Comment by dr-orlovsky** [comment]
Closed at the level of LNP/BP Standard library
